### ISSUE TITLE
Launch Vivado with VNC instead of X11 forwarding

### ISSUE THREAD

**Issue by ValentiWorkLearning** [ichi4096/vivado-on-silicon-mac#13]
Thank you for your work for launching Vivado on Apple silicon. I've implemented MVP for using all of this with the full UI instead of X11 forwarding. It allows to use normal flow without a such issue: https://github.com/ichi4096/vivado-on-silicon-mac/issues/12

The repo is placed here:
https://github.com/ValentiWorkLearning/vivado-on-silicon-mac_with_vnc

**Comment by ichi4096** [comment]
Cool!

Initially I also used vnc forwarding, but thought X11 forwarding lets you have the windows inside macOS and also allows for clipboard sharing. Unfortunately, the resolution sucks (the fonts are barely legible) and some dialogue windows are so tiny that no options are clickable.

Maybe vnc is better after all… But there are some GUI changes in the new version of Vivado anyway, so perhaps it behaves differently. I could also add an option to the installer to let the user choose between x11 and vnc.

**Comment by ValentiWorkLearning** [comment]
@ichi4096 it's definitely good idea to add vnc option for this tool. Also, I propose to add optional parameter for installer not to delete existing installation directory. It really takes a while to re-download everything again. What do you think about that?

**Comment by ichi4096** [comment]
The downloaded bin file isn‘t deleted though, right?

But yeah, I‘ll add a vnc option. I‘m thinking of making the whole tool GUI based instead of this bundle of scripts, so I‘ll probably add this there.

**Comment by ValentiWorkLearning** [comment]
@ichi4096 Yep, I've rechecked the scripts. Everything is fine with them.

**Comment by ichi4096** [comment]
Do you mean where the installer says "Installer was previously extracted. Removing the extracted directory" ? Because that's just the extraction of the web installer itself (the phase of the installation where a bunch of dots are displayed). The download of the actual Vivado program is deleted automatically by the installer, so there's little I can do about that.

**Comment by ichi4096** [comment]
Anyway, I'll close this issue since it's addressing the same problem as #12 .
