### ISSUE TITLE
IO_Init failed for xvcd?

### ISSUE THREAD

**Issue by hakatu** [ichi4096/vivado-on-silicon-mac#16]
I tried to install with the 2022.2 bin and everything seems fine. xvcd and launch_vivado app are turned on in Privacy & Security / Acessibility.

However, when I open Vivado, the Windows with ftdi would give the errors below and run continuously.

`ftdi_usb_open(0x0403, 0x6010): -3 (device not found)
io_init failed`

<img width="588" alt="Screenshot 2023-08-22 at 16 02 22" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/20923331/8c72d6d7-c18e-4e03-ab8e-925d4dee0559">

Is this suppose to happen? And will it work if I plug the board in? As I haven't got the board to try yet.

(Mac OS 13.5.1, M1 pro, 2022.2)

Will try 2023 later on to see if anything's different. Good project!

**Comment by ichi4096** [comment]
Yes, the xvcd binary outputs this as long as no device is plugged in. Even when you plug in your board, the error messages will be displayed as they are not cleared, but this can be ignored. Note that this version of xvcd only supports the FT2232C chip. Other boards may be supported by [this version](https://github.com/Xilinx/XilinxVirtualCable).
