### ISSUE TITLE
Question: Can this work from an external SSD/non-Download folder?

### ISSUE THREAD

**Issue by juanppalacios** [ichi4096/vivado-on-silicon-mac#18]
Thank you for updating the repo to include Vivado 2023.1. I am running this fine with a simple simulation. Now that I got it running, I am wondering if it were possible to move the folder to another location or would that break stuff? If not, do you think I can reinstall the tool in a desired folder?

**Comment by ichi4096** [comment]
I am unsure whether other installation directories work but running programs on an external SSD is always risky. I'm currently rewriting the scripts such that it should be supported in theory (though I don't have an external SSD to test this on).
