### ISSUE TITLE
Open Launch_Vivado.app with non-default folder

### ISSUE THREAD

**Issue by gri11** [ichi4096/vivado-on-silicon-mac#20]
Hello again 😄,
My goal now is connect Vivado with Basys 3 Board via USB.
I'm installed Vivado completed in folder name `vivado-on-silicon-mac-main 3`
I ran it. Got this error.
<img width="842" alt="image" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/60121937/29ab9c8c-4fef-4a4f-bad6-8865292ecd4e">
So, I use Launch_Vivado.app in broken installation folder name `vivado-on-silicon-mac-main`
And got this error.
<img width="842" alt="image" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/60121937/d84981f0-c382-4b99-8af8-aa6454587b58">
Current situation:
- no connection with Basys 3 board
<img width="579" alt="Screenshot 2566-09-04 at 9 37 17 PM" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/60121937/93d15928-0314-4d5b-a816-57ffa87c7692">

Connection
- Micro USB wire connected with board
- Micro USB wire connected with Macbook via USB-C hub.

Is there anyway that I can solve these problem?

**Comment by ichi4096** [comment]
Maybe there is an error because the path of the directory contains a space? Anyway, permission denied errors for the xvcd binary could possibly stem from you not allowing its execution in the Settings app, or because the file permissions aren't set correctly. Try `chmod +x xvcd` in a terminal.

The "device not found" errors are to be expected whenever the board isn't plugged in. When you do plug in the board, there is no success message and the errors aren't cleared. If the errors keep repeating, try `lsusb` in a terminal and see if your board is even picked up by your Mac.

**Comment by dmendat** [comment]
It's possible that the dongle isn't working well with the Mac? I've definitely had issues in the past with some USB dongles/hubs not working with embedded devices, for example.

**Comment by ichi4096** [comment]
I could get it to work with a dongle, the problem was with the micro usb cables, since a lot of them only have the power wires and no data wires.

**Comment by dmendat** [comment]
Yes that's definitely another common issue.

**Comment by gri11** [comment]
Oh I see, so I could try to connect my board with micro usb cable with power wires and data wires right?

**Comment by ichi4096** [comment]
Yes. xvcd could only connect to your board if it shows up in lsusb.

**Comment by gri11** [comment]
There're still error that existed when I already found the board in local machine:
<img width="842" alt="image" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/60121937/79b5afe6-b6d9-4c6b-8750-cbbef03c6add">

The error:
![image](https://github.com/ichi4096/vivado-on-silicon-mac/assets/60121937/575adec9-4fa4-43be-a618-248f32908c55)

**Comment by ichi4096** [comment]
Try first plugging in the board, then check with `lsusb` to make sure it's connected properly (the "Future Technology Devices International" device) and then opening up Vivado. If that doesn't work, does the xvcd terminal window display error messages?

**Comment by gri11** [comment]
For now this and error after I use [openFPGALoader](https://github.com/trabucayre/openFPGALoader) to load bitstring to the board
`bind: Address already in use`
<img width="842" alt="Screenshot 2566-09-05 at 8 31 12 PM" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/60121937/833af558-21cf-48e5-be3b-54a03dc0e612">

**Comment by ichi4096** [comment]
What command did you use exactly? Also make sure that no instance of xvcd is running since it will make the board unavalailable to any other program.

**Comment by gri11** [comment]
I use this command
`openFPGALoader -b basys3 main.bit` # Loading in SRAM
and
`openFPGALoader -b basys3 -f main.bit` # Writing in flash

**Comment by gri11** [comment]
No, when exited Vivado, xvcd will be exited too.
<img width="842" alt="image" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/60121937/104d2859-592e-43cf-b41b-0f255d729109">

**Comment by james-kollross** [comment]
I'm having a very similar issue with getting the hardware manager to connect to my Basys 3. It shows up in lsusb and in System Information, albeit only if I connect it through a USB hub and not directly with a dongle.
 
<img width="1229" alt="image" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/108961733/1599f126-fb1a-4687-9e37-9feb361d4e96">

lsusb result:
<img width="563" alt="image" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/108961733/3ed18c1e-480a-4a94-a1a6-17b6769207db">

**Comment by ichi4096** [comment]
I'm rewriting the script such that the docker instance will be logged in an open terminal window while xvcd has a little window of it's own, indicating that it is running / connected.

**Comment by ichi4096** [comment]
That rewrite has arrived about a year later : /
Please try the updated scripts. If the problems persist, open another issue.
