### ISSUE TITLE
GUI shows synthesis ongoing while logs show synthesis complete

### ISSUE THREAD

**Issue by mbvaughn21** [ichi4096/vivado-on-silicon-mac#22]
I installed vivado and built one of the example projects that it comes with. The GUI gets stuck at the synthesis step and never completes. However, in the logs it clearly shows that synthesis completed successfully.

This is the issue:
https://stackoverflow.com/questions/55733058/vivado-synthesis-hangs-in-docker-container-spawned-by-jenkins

It was indeed fixed by adding `--init` to all calls `docker run` 

For example:
```
# Run docker container by starting hw_server first to establish an XVC connection and then Vivado
echo "/usr/local/bin/docker run --init --rm --name vivado_container --mount type=bind,source=\"/tmp/.X11-unix\",target=\"/tmp/.X11-unix\" --mount type=bind,source=\""$script_dir"\",target=\"/home/user\" --platform linux/amd64 x64-linux sudo -H -u user bash /home/user/start_vivado.sh &" >> Launch_Vivado.app/Launch_Vivado
```

**Comment by ichi4096** [comment]
Thanks for pointing that out! I just added the flag to the `docker run` command.
