### ISSUE TITLE
xvcd can't be opened due to Apple not being able to check for malicious software

### ISSUE THREAD

**Issue by bhuiyah** [ichi4096/vivado-on-silicon-mac#23]
Hi, every time I try to open vivado, it works fine but I will get this pop-up.
<img width="272" alt="image" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/66151125/dd344d0a-b04c-4594-8bdd-d8fdef8c7609">
when I press show in finder, i get this: 
<img width="776" alt="image" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/66151125/cb89a502-cdcd-4342-b581-917818b4f403">
Is there anyway I can fix this issue?
<img width="582" alt="image" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/66151125/5e1904cd-8d38-40d9-a684-70d5efba18bc">

**Comment by ichi4096** [comment]
Stay tuned, I'm making a signed version of xvcd.

**Comment by ichi4096** [comment]
Ok, so I'm not able to sign it. There should theoretically be no problem running xvcd when done using terminal scripts, which is what I'm currently working on. Sorry for the delay.
