### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by RubiRubsn** [ichi4096/vivado-on-silicon-mac#25]
I have a problem with the installation. After being prompted to drag the installation file into the terminal window, I receive the following message:

Your account information seems to be wrong. Please try logging in again.
/home/user/docker.sh: line 57: /home/user/installer/xsetup: No such file or directory

I have created a Docker account and also logged in to the desktop application.

**Comment by fantinialex** [comment]
Hi, I use your issue to report some problems (and quick fixes) during installation.

1.  The **binary filename** passed must start with `Xilinx` (this solves your problem @RubiRubsn )
2. In the **docker.sh** file the hash to check versions is not working correctly anymore (lines 41 to 46), personally I set by hand `VIVADO_VERSION=2023`

I hope I helped someone, saving them time, who is running into the same problems as me

**Comment by RubiRubsn** [comment]
thanks
