### ISSUE TITLE
Vivado binary name has changed.

### ISSUE THREAD

**Issue by davidchisnall** [ichi4096/vivado-on-silicon-mac#27]
The installer is now called `FPGAs_AdaptiveSoCs_Unified_2023.2_1013_2256_Lin64.bin`, which means that `Xilinix*.bin` does not match.  Renaming it to add that prefix is a work around.

**Comment by ichi4096** [comment]
I am rewriting everything atm but [a bug in Rosetta emulation](https://developer.apple.com/forums/thread/746618?login=true) is currently undermining my efforts. Whenever they fix that, I'll upload an updated version.
