### ISSUE TITLE
how to launch vitis_hls

### ISSUE THREAD

**Issue by shahbaazlokh** [ichi4096/vivado-on-silicon-mac#3]
i am adding start_vitis_hls script here, but it did not worked on my system.
can you please add launch_vitis_hls.app same as launch_vivado

#!/bin/bash
cd /home/user\
export LD_PRELOAD="/lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libselinux.so.1 /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0"\
export JAVA_TOOL_OPTIONS="-Dsun.java2d.xrender=false"\
export JAVA_OPTS="-Dsun.java2d.xrender=false"\
export DISPLAY="host.docker.internal:0"\
/home/user/Xilinx/Vitis_HLS/*/settings64.sh\
/home/user/Xilinx/Vitis_HLS/*/bin/vitis_hls\
}

however i am not sure about LD_PRELOAD

thanks

**Comment by ichi4096** [comment]
I'll add additional apps such as Launch_Vitis, but starting vitis is not possible from the terminal right now, so I'll have to fix that first.

**Comment by shahbaazlokh** [comment]
i saw its not downloaded and installed, we will first have to download it and install it by adding in install_config.txt file

**Comment by ichi4096** [comment]
Still, right now, vitis_hls does not run inside of this docker container. I'll have to fix it.

**Comment by ichi4096** [comment]
The underlying error is the same as in issue #4.
