### ISSUE TITLE
The value specified in the configuration file for Modules 

### ISSUE THREAD

**Issue by deveshshevde** [ichi4096/vivado-on-silicon-mac#33]
@ichi4096 

ERROR - The value specified in the configuration file for Modules (Virtex UltraScale+ HBM:1,DocNav:1,Kintex UltraScale:1,Artix UltraScale+:1,Spartan-7:1,Artix-7:1,Virtex UltraScale+:1,Vitis Model Composer(Xilinx Toolbox for MATLAB and Simulink. Includes the functionality of System Generator for DSP):1,Zynq UltraScale+ MPSoC:1,Zynq-7000:1,Virtex UltraScale+ 58G:1,Kintex-7:1,Install Devices for Kria SOMs and Starter Kits:1,Kintex UltraScale+:1) is not valid.

<img width="1288" alt="Screenshot 2024-01-08 at 1 22 01 AM" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/61110768/cc3f0d2b-411f-4db3-a1c3-218359876791">'

**Comment by ichi4096** [comment]
This is due to #27 which I won't fix atm.
