### ISSUE TITLE
USB connection

### ISSUE THREAD

**Issue by mohay3069** [ichi4096/vivado-on-silicon-mac#34]
>USB connection
"A drawback of the Apple Virtualization framework is that there is no implementation for USB forwarding as of when I'm writing this. Therefore, these scripts set up the [Xilinx Virtual Cable protocol](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/644579329/Xilinx+Virtual+Cable). Intended to let a computer connect to an FPGA plugged into a remote computer, it allows for the host system to run an XVC server (in this case a software called [xvcd](https://github.com/tmbinc/xvcd) by Felix Domke), to which the docker container can connect.

xvcd is contained in this repository, but with slight changes to make it compile on modern day macOS (compilation requires libusb and libftdi installed via homebrew, though there is a compiled version included). It runs continuously while the docker container is running.

This version of xvcd only supports the FT2232C chip. There are forks of this software supporting other boards such as [xvcserver by Xilinx](https://github.com/Xilinx/XilinxVirtualCable)."

Will we ever see USB connection work on mac? i have a usb adapter on my mac and was wondering if it would work 

Thank you!

**Comment by ichi4096** [comment]
It is theoretically possible to have support to directly forward the USB connection to the Docker container but as of now there is no implementation of that. In the mean time, we're stuck with xvcd.
