### ISSUE TITLE
Error after dropping the binary

### ISSUE THREAD

**Issue by Krasnomakov** [ichi4096/vivado-on-silicon-mac#38]
Everything goes fine until I drop the binary into a terminal.
<img width="650" alt="Screenshot 2024-03-11 at 23 25 31" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/104280018/5eaa5b28-0399-43a2-bff5-efcc21e988a1">

Your account information seems to be wrong. Please try logging in again.
/home/user/docker.sh: line 57: /home/user/installer/xsetup: No such file or directory

**Comment by MelwynJoseph** [comment]
I had the same issue. The latest version seems to not prompt for login, trying it with a 2022 version binary allowed me to login just fine.

**Comment by ichi4096** [comment]
I'm in the middle of rewriting all of this to support newer versions of Vivado and add VNC support for a better GUI experience but newer versions of macOS [have a bug](https://developer.apple.com/forums/thread/746618?login=true) that makes running a particular VNC software impossible, so I'm stuck atm.
