### ISSUE TITLE
Vivado not launching

### ISSUE THREAD

**Issue by KrissPS** [ichi4096/vivado-on-silicon-mac#41]
I had to change x64-linux to ubuntu since that image is no longer available. Then I was able to download it. And now when I try to launch it I get this terminal, the vivado icon pops up for a moment and then disappears. If I am looking in docker it seems to start something for a split second.
<img width="568" alt="Screenshot 2024-04-30 at 14 25 06" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/71402282/053bb6b4-1441-4819-81f3-069963ff9406">
Fast help would be appreciated. I need this for Uni and other students in my module do so aswell.
<img width="730" alt="Screenshot 2024-04-30 at 14 26 54" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/71402282/abde50fd-44e1-443f-b97c-71c1790c0e3a">

**Comment by Adarsh063** [comment]
I am getting this type of message and after that I didn't able to launch vivado

**Comment by Adarsh063** [comment]
![Uploading IMG_20240712_133152.jpg…]()

**Comment by ichi4096** [comment]
I'm sorry the update is late, but there was an issue with Rosetta emulation, which made it difficult to effectively rewrite the scripts. This issue should be resolved now since newer versions of Vivado are supported.
