### ISSUE TITLE
Update Dockerfile to work with dependencies

### ISSUE THREAD

**Issue by leoegorov** [ichi4096/vivado-on-silicon-mac#42]
During installation I've had various unmet dependencies that resulted in the linux-64 image not being built. Please update the Dockerfile like this:

```
# Container for running Vivado on M1/M2 macs
# though it should work equally on Intel macs
FROM --platform=linux/amd64 ubuntu:20.04

# Update and install necessary packages
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends software-properties-common && \
    add-apt-repository -y universe && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    dbus dbus-x11 x11-utils xorg alsa-utils mesa-utils net-tools \
    libgl1-mesa-dri gtk2-engines lxappearance fonts-droid-fallback sudo firefox \
    ubuntu-gnome-default-settings ca-certificates curl gnupg lxde arc-theme \
    gtk2-engines-murrine gtk2-engines-pixbuf gnome-themes-extra nano xterm \
    python3-pip python3-dev build-essential git gcc-multilib g++ \
    ocl-icd-opencl-dev libjpeg62-dev libc6-dev-i386 graphviz make \
    unzip libtinfo5 libncursesw5 xvfb locales libswt-gtk-4-jni

# Create user "user" with password "pass"
RUN useradd --create-home --shell /bin/bash --user-group --groups adm,sudo user && \
    echo "user:pass" | chpasswd && \
    mkdir -p /home/user/.config/pcmanfm/LXDE/ && \
    ln -sf /usr/local/share/doro-lxde-wallpapers/desktop-items-0.conf \
    /home/user/.config/pcmanfm/LXDE/ && \
    chown -R user:user /home/user

# Set the locale, environment variables for XQuartz and Vivado
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV JAVA_TOOL_OPTIONS -Dsun.java2d.xrender=false
ENV JAVA_OPTS -Dsun.java2d.xrender=false
ENV DISPLAY host.docker.internal:0
ENV LD_PRELOAD /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libselinux.so.1 /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
```

**Comment by KrissPS** [comment]
did you do anything else in the other files like the installer?

**Comment by KrissPS** [comment]
Hey this worked until I got to dragging the file and I got this 
<img width="562" alt="Screenshot 2024-04-30 at 17 20 13" src="https://github.com/ichi4096/vivado-on-silicon-mac/assets/71402282/47ef10e8-8937-4891-90a0-bb0870f13605">

**Comment by hsadok** [comment]
I fixed the issue simply by changing it to use Ubuntu 22.04, as in here: https://github.com/ichi4096/vivado-on-silicon-mac/commit/6f061f8ab5ba1efe983dac9894d776074455dc5c

**Comment by KrissPS** [comment]
> I fixed the issue simply by changing it to use Ubuntu 22.04, as in here: [6f061f8](https://github.com/ichi4096/vivado-on-silicon-mac/commit/6f061f8ab5ba1efe983dac9894d776074455dc5c)

I tried this but I still get the login error

**Comment by hsadok** [comment]
I don't think your error is a login error. You are probably treating to install Vivado 23.2, which does not seem to be supported by the script. Try 23.1 instead.

**Comment by ichi4096** [comment]
I've updated the scripts which should resolve the dependency as well as the Vivado version issue. Please try with the new scripts and open a new issue should there be any further problems.
