### ISSUE TITLE
Package dependency issue in latest ubuntu

### ISSUE THREAD

**Issue by vantaa89** [ichi4096/vivado-on-silicon-mac#48]
Hi, I tried to install vivado by this repo, but I failed building the docker image. It seems like the issue originates from the installation of dependencies. 

In the `Dockerfile`, the line 

```
# install gui
RUN apt install -y --no-install-recommends --allow-unauthenticated \
dbus dbus-x11 x11-utils xorg alsa-utils mesa-utils net-tools \
libgl1-mesa-dri gtk2-engines lxappearance fonts-droid-fallback sudo firefox \
ubuntu-gnome-default-settings ca-certificates curl gnupg lxde arc-theme \
gtk2-engines-murrine gtk2-engines-pixbuf gnome-themes-standard nano xterm
```

tries to install a long list of packages. However, as of now, the package [`gnome-themes-standard`](https://packages.ubuntu.com/search?keywords=gnome-themes-standard) here does not seem to support any versions after `22.04LTS`.

As a temporary solution, I have modified the first (uncommented) line of the `Dockerfile` to install the `22.04` version of ubuntu:
 
```
FROM --platform=linux/amd64 ubuntu:22.04
```

Although this worked for me, I think the package needs to be replaced, unless it begins to support the newest version of ubuntu.

**Comment by ichi4096** [comment]
I have addressed this issue in the latest update to my scripts. For now, Ubuntu 22.04 is specified because if it ain't broke don't fix it. I doubt Vivado officially supports the latest Ubuntu anyway. I might change the GUI setup anyway.
