### ISSUE TITLE
Invalid installer hash

### ISSUE THREAD

**Issue by FlavioMili** [ichi4096/vivado-on-silicon-mac#56]
I get this error message after I select the resolution (standard one) whenever I try to install.

**Comment by ichi4096** [comment]
Could You share the exact terminal output / screenshot?

The hash of the installation binary You downloaded is checked in the beginning of the setup, so it should be ok. What can happen is when downloading additional content (right after choosing the resolution), that content can be corrupted and [sometimes the installer can't recover from that](https://github.com/ichi4096/vivado-on-silicon-mac/discussions/53#discussioncomment-10583897). In that case, simply retry the installation but make sure to run "cleanup.sh" beforehand or download my repository into a new folder.

**Comment by FlavioMili** [comment]
<img width="667" alt="Screenshot 2024-09-23 at 17 59 59" src="https://github.com/user-attachments/assets/ba378bc4-632f-45f8-8254-a7b860fcbb64">
this is the problem, I also tried to move the file inside the source directory and outside

**Comment by ichi4096** [comment]
This seems weird... But I can tell from the terminal output that the cleanup of leftover files hasn't fully taken place. Please delete this folder and download the newest zip file from my repository.

**Comment by FlavioMili** [comment]
<img width="723" alt="Screenshot 2024-09-23 at 18 54 51" src="https://github.com/user-attachments/assets/97b504d3-0f47-4d0c-ac93-673d22cb52d5">

now it is like this, previously it was a problem with the name of the file from amd website containing white space

**Comment by ichi4096** [comment]
Well... unfortunately You have too little disk space as mentioned in the second last line.

**Comment by FlavioMili** [comment]
Does it mean that it might need more than 100GB?

**Comment by ichi4096** [comment]
It needs around 100GB, possibly more.
